In [1]:
import pandas as pd
import pandas as pd
import numpy as np
from scipy.stats import norm
from scipy import stats
from scipy.stats import ttest_ind 
import matplotlib.pyplot as plt 
import seaborn as sns
import openpyxl

In [2]:
#import packages

In [ ]:
#3.	Does the vaccination rate decrease after the California stay-at-home was lifted (June 15, 2021) compare after 30, 60, and 90 days?
#4.	Does the vaccination rate decrease after the California stay-at-home was lifted (June 15, 2021) compared to the 4 largest counties?

In [5]:
rona_d=pd.read_csv("/Users/arkajiad/Downloads/Covid Vaccine Datasets only/covid19vaccinesbycounty.csv")

In [7]:
rona_d.head(13)

,county,administered_date,total_doses,cumulative_total_doses,pfizer_doses,cumulative_pfizer_doses,moderna_doses,cumulative_moderna_doses,jj_doses,cumulative_jj_doses,partially_vaccinated,total_partially_vaccinated,fully_vaccinated,cumulative_fully_vaccinated,at_least_one_dose,cumulative_at_least_one_dose,california_flag,booster_recip_count,cumulative_booster_recip_count
0,Alameda,2020-01-05,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,0,0
1,Alameda,2020-07-27,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,0,0
2,Alameda,2020-07-29,0,1,0,0,0,1,0,0,0,1,0,0,0,1,NaN,0,0
3,Alameda,2020-07-30,0,1,0,0,0,1,0,0,0,1,0,0,0,1,NaN,0,0
4,Alameda,2020-07-31,0,1,0,0,0,1,0,0,0,1,0,0,0,1,NaN,0,0
5,Alameda,2020-08-01,0,1,0,0,0,1,0,0,0,1,0,0,0,1,NaN,0,0
6,Alameda,2020-08-02,0,1,0,0,0,1,0,0,0,1,0,0,0,1,NaN,0,0
7,Alameda,2020-08-03,0,1,0,0,0,1,0,0,0,1,0,0,0,1,NaN,0,0
8,Alameda,2020-08-04,0,1,0,0,0,1,0,0,0,1,0,0,0,1,NaN,0,0
9,Alameda,2020-08-05,0,1,0,0,0,1,0,0,0,1,0,0,0,1,NaN,0,0
10,Alameda,2020-08-06,0,1,0,0,0,1,0,0,0,1,0,0,0,1,NaN,0,0
11,Alameda,2020-08-07,0,1,0,0,0,1,0,0,0,1,0,0,0,1,NaN,0,0
12,Alameda,2020-08-08,0,1,0,0,0,1,0,0,0,1,0,0,0,1,NaN,0,0

In [14]:
rona_d.tail(13)

,county,administered_date,total_doses,cumulative_total_doses,pfizer_doses,cumulative_pfizer_doses,moderna_doses,cumulative_moderna_doses,jj_doses,cumulative_jj_doses,partially_vaccinated,total_partially_vaccinated,fully_vaccinated,cumulative_fully_vaccinated,at_least_one_dose,cumulative_at_least_one_dose,california_flag,booster_recip_count,cumulative_booster_recip_count
40597,Yuba,2022-04-29,68,95080,28,38629,38,49005,0,4771,3,3685,5,38733,3,42418,California,19,16442
40598,Yuba,2022-04-30,19,95099,8,38637,10,49015,1,4772,1,3682,5,38738,2,42420,California,5,16447
40599,Yuba,2022-05-01,16,95115,12,38649,4,49019,0,4772,3,3681,4,38742,3,42423,California,3,16450
40600,Yuba,2022-05-02,43,95158,17,38666,25,49044,1,4773,6,3685,3,38745,7,42430,California,5,16455
40601,Yuba,2022-05-03,52,95210,21,38687,28,49072,2,4775,2,3681,8,38753,4,42434,California,11,16466
40602,Yuba,2022-05-04,53,95263,18,38705,33,49105,0,4775,11,3690,2,38755,11,42445,California,13,16479
40603,Yuba,2022-05-05,61,95324,18,38723,39,49144,0,4775,12,3696,6,38761,12,42457,California,11,16490
40604,Yuba,2022-05-06,71,95395,28,38751,35,49179,0,4775,7,3693,10,38771,7,42464,California,20,16510
40605,Yuba,2022-05-07,22,95417,11,38762,8,49187,0,4775,3,3690,6,38777,3,42467,California,3,16513
40606,Yuba,2022-05-08,13,95430,8,38770,5,49192,0,4775,1,3691,0,38777,1,42468,California,11,16524
40607,Yuba,2022-05-09,48,95478,15,38785,31,49223,0,4775,8,3691,8,38785,8,42476,California,11,16535
40608,Yuba,2022-05-10,74,95552,25,38810,45,49268,1,4776,8,3691,9,38794,9,42485,California,20,16555
40609,Yuba,2022-05-11,42,95594,7,38817,33,49301,0,4776,3,3687,7,38801,3,42488,California,7,16562

In [15]:
rona_d.isnull().sum()

county                               0
administered_date                    0
total_doses                          0
cumulative_total_doses               0
pfizer_doses                         0
cumulative_pfizer_doses              0
moderna_doses                        0
cumulative_moderna_doses             0
jj_doses                             0
cumulative_jj_doses                  0
partially_vaccinated                 0
total_partially_vaccinated           0
fully_vaccinated                     0
cumulative_fully_vaccinated          0
at_least_one_dose                    0
cumulative_at_least_one_dose         0
california_flag                   8964
booster_recip_count                  0
cumulative_booster_recip_count       0
dtype: int64