In [2]:
#importing packages that will be needed to test the data

In [1]:
import pandas as pd
import pandas as pd
import numpy as np
from scipy.stats import norm
from scipy import stats
from scipy.stats import ttest_ind 
import matplotlib.pyplot as plt 
import seaborn as sns
import openpyxl

In [2]:
#importing the data I will be using

In [3]:
covid=pd.read_csv('Data/covid19vaccinesbycounty.csv')

In [4]:
#this is 10 rows of data to see some data a glance

In [5]:
covid.head(11)

,county,administered_date,total_doses,cumulative_total_doses,pfizer_doses,cumulative_pfizer_doses,moderna_doses,cumulative_moderna_doses,jj_doses,cumulative_jj_doses,partially_vaccinated,total_partially_vaccinated,fully_vaccinated,cumulative_fully_vaccinated,at_least_one_dose,cumulative_at_least_one_dose,california_flag,booster_recip_count,cumulative_booster_recip_count
0,Alameda,2020-01-05,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,0,0
1,Alameda,2020-07-27,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,0,0
2,Alameda,2020-07-29,0,1,0,0,0,1,0,0,0,1,0,0,0,1,NaN,0,0
3,Alameda,2020-07-30,0,1,0,0,0,1,0,0,0,1,0,0,0,1,NaN,0,0
4,Alameda,2020-07-31,0,1,0,0,0,1,0,0,0,1,0,0,0,1,NaN,0,0
5,Alameda,2020-08-01,0,1,0,0,0,1,0,0,0,1,0,0,0,1,NaN,0,0
6,Alameda,2020-08-02,0,1,0,0,0,1,0,0,0,1,0,0,0,1,NaN,0,0
7,Alameda,2020-08-03,0,1,0,0,0,1,0,0,0,1,0,0,0,1,NaN,0,0
8,Alameda,2020-08-04,0,1,0,0,0,1,0,0,0,1,0,0,0,1,NaN,0,0
9,Alameda,2020-08-05,0,1,0,0,0,1,0,0,0,1,0,0,0,1,NaN,0,0
10,Alameda,2020-08-06,0,1,0,0,0,1,0,0,0,1,0,0,0,1,NaN,0,0

In [6]:
#Imported another dataset

In [7]:
county=pd.read_csv('Data/covid19vaccinesbycounty.csv')

In [8]:
doses=pd.read_csv('Data/covid19vaccinesadministeredbydemographics.csv')

In [9]:
doses.head()

,demographic_category,demographic_value,administered_date,total_doses,cumulative_total_doses,pfizer_doses,cumulative_pfizer_doses,moderna_doses,cumulative_moderna_doses,jj_doses,cumulative_jj_doses,partially_vaccinated,total_partially_vaccinated,fully_vaccinated,cumulative_fully_vaccinated,at_least_one_dose,cumulative_at_least_one_dose,booster_recip_count,cumulative_booster_recip_count,booster_eligible_population
0,Age Group,18-49,2022-05-24,4691,34103581,2940,20171196,1674,12598288,64,1320403,809,1616426,573,13266106,848,14882532,2349,6751750,12826658
1,Age Group,50-64,2022-05-24,9419,17348656,5001,9212374,4368,7375220,31,745494,337,577825,330,6243630,350,6821455,1410,4047712,6114559
2,Age Group,65+,2022-05-24,14213,16417987,6963,7728306,7185,8422995,21,246821,334,484580,398,5508377,338,5992957,1332,4092974,5411735
3,Age Group,12-17,2022-05-24,1144,5414757,1141,5398601,3,11305,0,1342,169,224073,157,2116037,169,2340110,801,700520,1964037
4,Age Group,5-11,2022-05-24,2570,2702236,2569,2699203,0,1798,0,238,555,185584,538,1236883,555,1422467,1476,14715,0

In [10]:
pwd

'/Users/jin/Desktop/Final-Project-'

In [11]:
#i used the code concat to merge

In [12]:
covid2=pd.concat([covid,county,doses])

In [13]:
covid2.head(11)

,county,administered_date,total_doses,cumulative_total_doses,pfizer_doses,cumulative_pfizer_doses,moderna_doses,cumulative_moderna_doses,jj_doses,cumulative_jj_doses,...,fully_vaccinated,cumulative_fully_vaccinated,at_least_one_dose,cumulative_at_least_one_dose,california_flag,booster_recip_count,cumulative_booster_recip_count,demographic_category,demographic_value,booster_eligible_population
0,Alameda,2020-01-05,0,0,0,0,0,0,0,0,...,0,0,0,0,NaN,0,0,NaN,NaN,NaN
1,Alameda,2020-07-27,0,0,0,0,0,0,0,0,...,0,0,0,0,NaN,0,0,NaN,NaN,NaN
2,Alameda,2020-07-29,0,1,0,0,0,1,0,0,...,0,0,0,1,NaN,0,0,NaN,NaN,NaN
3,Alameda,2020-07-30,0,1,0,0,0,1,0,0,...,0,0,0,1,NaN,0,0,NaN,NaN,NaN
4,Alameda,2020-07-31,0,1,0,0,0,1,0,0,...,0,0,0,1,NaN,0,0,NaN,NaN,NaN
5,Alameda,2020-08-01,0,1,0,0,0,1,0,0,...,0,0,0,1,NaN,0,0,NaN,NaN,NaN
6,Alameda,2020-08-02,0,1,0,0,0,1,0,0,...,0,0,0,1,NaN,0,0,NaN,NaN,NaN
7,Alameda,2020-08-03,0,1,0,0,0,1,0,0,...,0,0,0,1,NaN,0,0,NaN,NaN,NaN
8,Alameda,2020-08-04,0,1,0,0,0,1,0,0,...,0,0,0,1,NaN,0,0,NaN,NaN,NaN
9,Alameda,2020-08-05,0,1,0,0,0,1,0,0,...,0,0,0,1,NaN,0,0,NaN,NaN,NaN
10,Alameda,2020-08-06,0,1,0,0,0,1,0,0,...,0,0,0,1,NaN,0,0,NaN,NaN,NaN

In [14]:
# inputing isnull code to see all data that has null

In [15]:
covid2.isnull().sum()

county                            11027
administered_date                     0
total_doses                           0
cumulative_total_doses                0
pfizer_doses                          0
cumulative_pfizer_doses               0
moderna_doses                         0
cumulative_moderna_doses              0
jj_doses                              0
cumulative_jj_doses                   0
partially_vaccinated                  0
total_partially_vaccinated            0
fully_vaccinated                      0
cumulative_fully_vaccinated           0
at_least_one_dose                     0
cumulative_at_least_one_dose          0
california_flag                   28955
booster_recip_count                   0
cumulative_booster_recip_count        0
demographic_category              81220
demographic_value                 81220
booster_eligible_population       81220
dtype: int64

In [16]:
#inputing notnull code to view data that has data

In [17]:
covid2.notnull().head()

,county,administered_date,total_doses,cumulative_total_doses,pfizer_doses,cumulative_pfizer_doses,moderna_doses,cumulative_moderna_doses,jj_doses,cumulative_jj_doses,...,fully_vaccinated,cumulative_fully_vaccinated,at_least_one_dose,cumulative_at_least_one_dose,california_flag,booster_recip_count,cumulative_booster_recip_count,demographic_category,demographic_value,booster_eligible_population
0,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,False,True,True,False,False,False
1,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,False,True,True,False,False,False
2,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,False,True,True,False,False,False
3,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,False,True,True,False,False,False
4,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,False,True,True,False,False,False

In [18]:
covid2.shape

(92247, 22)

In [19]:
# this is 10 rows of the dataset with the missing data removed

In [20]:
covid2.head()

,county,administered_date,total_doses,cumulative_total_doses,pfizer_doses,cumulative_pfizer_doses,moderna_doses,cumulative_moderna_doses,jj_doses,cumulative_jj_doses,...,fully_vaccinated,cumulative_fully_vaccinated,at_least_one_dose,cumulative_at_least_one_dose,california_flag,booster_recip_count,cumulative_booster_recip_count,demographic_category,demographic_value,booster_eligible_population
0,Alameda,2020-01-05,0,0,0,0,0,0,0,0,...,0,0,0,0,NaN,0,0,NaN,NaN,NaN
1,Alameda,2020-07-27,0,0,0,0,0,0,0,0,...,0,0,0,0,NaN,0,0,NaN,NaN,NaN
2,Alameda,2020-07-29,0,1,0,0,0,1,0,0,...,0,0,0,1,NaN,0,0,NaN,NaN,NaN
3,Alameda,2020-07-30,0,1,0,0,0,1,0,0,...,0,0,0,1,NaN,0,0,NaN,NaN,NaN
4,Alameda,2020-07-31,0,1,0,0,0,1,0,0,...,0,0,0,1,NaN,0,0,NaN,NaN,NaN

In [21]:
covid2.tail(20)

,county,administered_date,total_doses,cumulative_total_doses,pfizer_doses,cumulative_pfizer_doses,moderna_doses,cumulative_moderna_doses,jj_doses,cumulative_jj_doses,...,fully_vaccinated,cumulative_fully_vaccinated,at_least_one_dose,cumulative_at_least_one_dose,california_flag,booster_recip_count,cumulative_booster_recip_count,demographic_category,demographic_value,booster_eligible_population
11007,NaN,2020-07-29,6,11,0,0,6,11,0,0,...,0,0,6,11,NaN,0,0,Race/Ethnicity,White,9374847.0
11008,NaN,2020-07-29,2,5,0,3,2,2,0,0,...,0,0,2,5,NaN,0,0,Race/Ethnicity,Latino,7975254.0
11009,NaN,2020-07-28,3,5,1,3,2,2,0,0,...,0,0,2,4,NaN,0,0,Age Group,18-49,12826658.0
11010,NaN,2020-07-28,3,4,0,1,3,3,0,0,...,0,0,3,4,NaN,0,0,Age Group,65+,5411735.0
11011,NaN,2020-07-28,4,5,1,2,3,3,0,0,...,0,0,4,5,NaN,0,0,Gender,Female,13728925.0
11012,NaN,2020-07-28,2,5,0,2,2,3,0,0,...,0,0,2,5,NaN,0,0,Gender,Male,12551052.0
11013,NaN,2020-07-28,4,5,0,0,4,5,0,0,...,0,0,4,5,NaN,0,0,Race/Ethnicity,White,9374847.0
11014,NaN,2020-07-28,1,3,1,3,0,0,0,0,...,0,0,1,3,NaN,0,0,Race/Ethnicity,Latino,7975254.0
11015,NaN,2020-07-28,1,1,0,0,1,1,0,0,...,0,0,1,1,NaN,0,0,Race/Ethnicity,Other Race,1818341.0
11016,NaN,2020-07-27,1,2,1,2,0,0,0,0,...,0,0,1,2,NaN,0,0,Age Group,18-49,12826658.0
11017,NaN,2020-07-27,1,1,1,1,0,0,0,0,...,0,0,1,1,NaN,0,0,Age Group,65+,5411735.0
11018,NaN,2020-07-27,1,1,0,0,1,1,0,0,...,0,0,1,1,NaN,0,0,Age Group,50-64,6114559.0
11019,NaN,2020-07-27,2,3,1,2,1,1,0,0,...,0,0,2,3,NaN,0,0,Gender,Male,12551052.0
11020,NaN,2020-07-27,1,1,1,1,0,0,0,0,...,0,0,1,1,NaN,0,0,Gender,Female,13728925.0
11021,NaN,2020-07-27,1,2,1,2,0,0,0,0,...,0,0,1,2,NaN,0,0,Race/Ethnicity,Latino,7975254.0
11022,NaN,2020-07-27,1,1,0,0,1,1,0,0,...,0,0,1,1,NaN,0,0,Race/Ethnicity,White,9374847.0
11023,NaN,2020-07-27,1,1,1,1,0,0,0,0,...,0,0,1,1,NaN,0,0,Race/Ethnicity,Unknown,772110.0
11024,NaN,2020-01-05,1,1,1,1,0,0,0,0,...,0,0,1,1,NaN,0,0,Age Group,18-49,12826658.0
11025,NaN,2020-01-05,1,1,1,1,0,0,0,0,...,0,0,1,1,NaN,0,0,Gender,Male,12551052.0
11026,NaN,2020-01-05,1,1,1,1,0,0,0,0,...,0,0,1,1,NaN,0,0,Race/Ethnicity,Latino,7975254.0

In [22]:
#inputing info code to see column names and type of data (interger, object)

In [23]:
covid2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 92247 entries, 0 to 11026
Data columns (total 22 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   county                          81220 non-null  object
 1   administered_date               92247 non-null  object
 2   total_doses                     92247 non-null  int64
 3   cumulative_total_doses          92247 non-null  int64
 4   pfizer_doses                    92247 non-null  int64
 5   cumulative_pfizer_doses         92247 non-null  int64
 6   moderna_doses                   92247 non-null  int64
 7   cumulative_moderna_doses        92247 non-null  int64
 8   jj_doses                        92247 non-null  int64
 9   cumulative_jj_doses             92247 non-null  int64
 10  partially_vaccinated            92247 non-null  int64
 11  total_partially_vaccinated      92247 non-null  int64
 12  fully_vaccinated                92247 non-null  int64
 13  cumulative_fully_vaccinated     92247 non-null  int64
 14  at_least_one_dose               92247 non-null  int64
 15  cumulative_at_least_one_dose    92247 non-null  int64
 16  california_flag                 63292 non-null  object
 17  booster_recip_count             92247 non-null  int64
 18  cumulative_booster_recip_count  92247 non-null  int64
 19  demographic_category            11027 non-null  object
 20  demographic_value               11027 non-null  object
 21  booster_eligible_population     11027 non-null  float64
dtypes: float64(1), int64(16), object(5)
memory usage: 16.2+ MB

In [24]:
covid2.columns

Index(['county', 'administered_date', 'total_doses', 'cumulative_total_doses',
       'pfizer_doses', 'cumulative_pfizer_doses', 'moderna_doses',
       'cumulative_moderna_doses', 'jj_doses', 'cumulative_jj_doses',
       'partially_vaccinated', 'total_partially_vaccinated',
       'fully_vaccinated', 'cumulative_fully_vaccinated', 'at_least_one_dose',
       'cumulative_at_least_one_dose', 'california_flag',
       'booster_recip_count', 'cumulative_booster_recip_count',
       'demographic_category', 'demographic_value',
       'booster_eligible_population'],
      dtype='object')

In [29]:
covid2.isnull().sum()

county                            11027
administered_date                     0
total_doses                           0
cumulative_total_doses                0
pfizer_doses                          0
cumulative_pfizer_doses               0
moderna_doses                         0
cumulative_moderna_doses              0
jj_doses                              0
cumulative_jj_doses                   0
partially_vaccinated                  0
total_partially_vaccinated            0
fully_vaccinated                      0
cumulative_fully_vaccinated           0
at_least_one_dose                     0
cumulative_at_least_one_dose          0
california_flag                   28955
booster_recip_count                   0
cumulative_booster_recip_count        0
demographic_category              81220
demographic_value                 81220
booster_eligible_population       81220
dtype: int64

In [41]:
covid2.head(20)

,county,administered_date,total_doses,cumulative_total_doses,pfizer_doses,cumulative_pfizer_doses,moderna_doses,cumulative_moderna_doses,jj_doses,cumulative_jj_doses,...,fully_vaccinated,cumulative_fully_vaccinated,at_least_one_dose,cumulative_at_least_one_dose,california_flag,booster_recip_count,cumulative_booster_recip_count,demographic_category,demographic_value,booster_eligible_population
0,Alameda,2020-01-05,0,0,0,0,0,0,0,0,...,0,0,0,0,NaN,0,0,NaN,NaN,NaN
1,Alameda,2020-07-27,0,0,0,0,0,0,0,0,...,0,0,0,0,NaN,0,0,NaN,NaN,NaN
2,Alameda,2020-07-29,0,1,0,0,0,1,0,0,...,0,0,0,1,NaN,0,0,NaN,NaN,NaN
3,Alameda,2020-07-30,0,1,0,0,0,1,0,0,...,0,0,0,1,NaN,0,0,NaN,NaN,NaN
4,Alameda,2020-07-31,0,1,0,0,0,1,0,0,...,0,0,0,1,NaN,0,0,NaN,NaN,NaN
5,Alameda,2020-08-01,0,1,0,0,0,1,0,0,...,0,0,0,1,NaN,0,0,NaN,NaN,NaN
6,Alameda,2020-08-02,0,1,0,0,0,1,0,0,...,0,0,0,1,NaN,0,0,NaN,NaN,NaN
7,Alameda,2020-08-03,0,1,0,0,0,1,0,0,...,0,0,0,1,NaN,0,0,NaN,NaN,NaN
8,Alameda,2020-08-04,0,1,0,0,0,1,0,0,...,0,0,0,1,NaN,0,0,NaN,NaN,NaN
9,Alameda,2020-08-05,0,1,0,0,0,1,0,0,...,0,0,0,1,NaN,0,0,NaN,NaN,NaN
10,Alameda,2020-08-06,0,1,0,0,0,1,0,0,...,0,0,0,1,NaN,0,0,NaN,NaN,NaN
11,Alameda,2020-08-07,0,1,0,0,0,1,0,0,...,0,0,0,1,NaN,0,0,NaN,NaN,NaN
12,Alameda,2020-08-08,0,1,0,0,0,1,0,0,...,0,0,0,1,NaN,0,0,NaN,NaN,NaN
13,Alameda,2020-08-09,0,1,0,0,0,1,0,0,...,0,0,0,1,NaN,0,0,NaN,NaN,NaN
14,Alameda,2020-08-11,0,5,0,4,0,1,0,0,...,0,0,0,5,NaN,0,0,NaN,NaN,NaN
15,Alameda,2020-08-16,0,10,0,8,0,2,0,0,...,0,0,0,10,NaN,0,0,NaN,NaN,NaN
16,Alameda,2020-08-24,0,24,0,21,0,3,0,0,...,0,0,0,24,NaN,0,0,NaN,NaN,NaN
17,Alameda,2020-08-29,0,34,0,30,0,4,0,0,...,0,0,0,34,NaN,0,0,NaN,NaN,NaN
18,Alameda,2020-08-30,0,34,0,30,0,4,0,0,...,0,0,0,34,NaN,0,0,NaN,NaN,NaN
19,Alameda,2020-09-05,0,49,0,44,0,5,0,0,...,0,8,0,40,NaN,0,0,NaN,NaN,NaN